import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    h1: {
        fontWeight: '700',
        fontSize: 22,
        color: '#000000',
    },
    h3: {
        fontWeight: '700',
        fontSize: 18,
        color: '#000000',
    },
    h4: {
        fontWeight: '700',
        fontSize: 14,
        color: '#000000',
    },
    alert: {
        backgroundColor: '#ff0000',
        height: 10,
        width: 10,
        borderRadius: 5,
        position: 'absolute',
        zIndex: 9,
        top: 15,
        left: 45,
    },
    error: {
        color: 'red',
        width: '100%',
        textAlign: 'left',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    tabBar: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        backgroundColor: '#ffffff',
        flexDirection: 'row',
        paddingBottom: 30,
    },
    deviceStatus: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#D8D8D8',
    },
    stepProgress: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 30,
    },
    progressDot: {
        height: 25,
        width: 25,
        borderRadius: 25 / 2,
        backgroundColor: '#94CB2A',
    },
    progressSpacer: {
        height: 2,
        width: 100,
        backgroundColor: '#94CB2A',
    },
    labelSpacer: {
        height: 2,
        width: 75,
    },
    imageBox: {
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    stepProgressLabel: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 50,
        marginBottom: 0,
    },
    progressLabel: {
        height: 25,
        width: 50,
    },
    statusTitle: {
        width: 125,
    },
    statusValue: {
        flex: 1,
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
    },
    statusText: {
        flex: 1,
        textAlign: 'right',
        fontWeight: '300',
        maxWidth: 250,
    },
    statusEdit: {
        width: 60,
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
    },
    text: {
        fontWeight: 'normal',
        fontSize: 16,
        color: '#000000',
    },
    appContainer: {
        backgroundColor: '#F3F5F7',
        flex: 1,
        alignItems: 'center',
        marginBottom: 0,
    },
    loginBox: {
        backgroundColor: '#F3F5F7',
        flex: 1,
        alignItems: 'center',
        marginBottom: 0,
    },
    title: {
        marginTop: 50,
        flex: 0.35,
        alignItems: 'center',
        justifyContent: 'center',
    },
    titleBar: {
        marginTop: 10,
        flex: 0.15,
        alignItems: 'center',
        justifyContent: 'center',
    },
    titleWrapper: {
        flex: 0.35,
        marginTop: 50,
        alignItems: 'center',
        justifyContent: 'center',
    },
    textWrapper: {
        flex: 0.15,
        margin: 8,
        marginBottom: 20,
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    setupBox: {
        marginTop: 50,
        flex: 1,
        alignItems: 'center',
    },
    textBox: {
        width: '90%',
        fontSize: 12,
        marginBottom: 20,
    },
    formBox: {
        backgroundColor: '#F3F5F7',
        flex: 1,
        width: '90%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    formField: {
        backgroundColor: '#ffffff',
        borderRadius: 5,
        borderColor: 'rgba(174, 174, 192, .7)',
        borderStyle: 'solid',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        marginBottom: 10,
        paddingLeft: 5,
        paddingRight: 5,
        paddingBottom: 10,
        paddingTop: 10,
    },
    pickerContatiner: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderRadius: 5,
        borderColor: 'rgba(174, 174, 192, .7)',
        borderStyle: 'solid',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        marginBottom: 10,
        paddingLeft: 5,
        paddingRight: 5,
        paddingBottom: 10,
        paddingTop: 10,
        marginHorizontal: 3,
    },
    spacer: {
        height: 50,
        width: '100%',
    },
    loginLabel: {
        color: '#2E353C',
        width: '95%',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        textAlign: 'left',
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
    },
    stateDropDown: {
        padding: 5,
        backgroundColor: '#ffffff',
        position: 'absolute',
        width: '100%',
        height: 200,
        bottom: -205,
        zIndex: 9,
    },
    label: {
        width: '95%',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        textAlign: 'left',
    },
    caption: {
        fontStyle: 'italic',
        fontSize: 12,
        width: '95%',
        marginBottom: 20,
        color: '#697179',
    },
    loginInput: {
        borderColor: '#979797',
        borderWidth: 0,
        padding: 0,
        marginTop: 5,
        marginBottom: 5,
        width: '95%',
        fontSize: 18,
        fontWeight: '300',
    },
    textInput: {
        borderColor: '#979797',
        padding: 0,
        marginTop: 5,
        marginBottom: 5,
        width: '95%',
        fontSize: 18,
        fontWeight: '300',
    },

    separator: {
        height: '100%',
        width: 1,
        backgroundColor: 'rgba(151,151,151,0.5)',
    },
    button: {
        borderColor: '#979797',
        borderWidth: 0,
        backgroundColor: '#ffffff',
        color: '#000000',
        padding: 10,
        margin: 10,
        shadowOffset: {width: 0, height: 5},
        shadowRadius: 5,
        shadowColor: 'black',
        shadowOpacity: 0.07,
        elevation: 1,
    },
    buttonGroupHz: {
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
    },
    buttonGroup: {
        borderColor: '#979797',
        borderWidth: 1,
        width: '100%',
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        borderRadius: 5,
        overflow: 'hidden',
    },
    recircButton: {
        shadowOffset: {width: 0, height: 5},
        shadowRadius: 5,
        shadowColor: 'black',
        shadowOpacity: 0.07,
        elevation: 0.5,
    },
    banner: {
        height: 200,
        textAlign: 'center',
        fontWeight: '500',
        fontSize: 14,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        overflow: 'hidden',
        shadowOffset: {width: 0, height: 5},
        shadowRadius: 8,
        shadowColor: 'black',
        shadowOpacity: 0.05,
        elevation: 1,
    },
    itemWindow: {
        width: '100%',
        backgroundColor: '#ffffff',
        borderRadius: 10,
        padding: 15,
        shadowOffset: {width: 0, height: 5},
        shadowRadius: 8,
        shadowColor: 'black',
        shadowOpacity: 0.05,
        elevation: 1,
    },
    recircWindow: {
        width: '100%',
        backgroundColor: '#EEF1F4',
        borderRadius: 10,
        paddingTop: 5,
        paddingBottom: 5,
        justifyContent: 'center',
    },
    deviceHeader: {
        flexDirection: 'row',
        height: 20,
        marginBottom: 20,
    },
    wifiHeader: {
        flexDirection: 'row',
        height: 20,
        marginBottom: 20,
    },
    deviceName: {
        flex: 1,
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    deviceWifi: {
        flex: 0.8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    itemStatus: {
        flexDirection: 'row',
    },
    itemDescription: {
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    itemIcon: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    tankItemIcon: {
        position: 'absolute',
        right: 15,
        bottom: 0,
    },
    wifiSelect: {
        width: '100%',
        backgroundColor: 'transparent',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        borderBottomWidth: 1,
        borderBottomColor: '#E1E5E8',
    },
    signal: {
        width: 20,
        margin: 5,
        backgroundColor: 'transparent',
    },
    ssid: {
        width: 120,
        marginLeft: 15,
        fontWeight: '300',
        color: '#000000',
    },
    timezoneTime: {
        marginLeft: 15,
        fontWeight: '300',
        color: '#000000',
    },
    setup: {
        flexDirection: 'row',
    },
    setupItem: {
        flex: 0.25,
        padding: 10,
    },
    setupInstruction: {
        flex: 1,
    },
    stopIcon: {
        height: 30,
        width: 30,
        backgroundColor: '#ffffff',
        position: 'absolute',
    },
    passwordContainer: {
        flexDirection: 'row',
    },
    secureInputStyle: {
        flex: 1,
        borderColor: '#979797',
        borderWidth: 0,
        padding: 0,
        marginTop: 5,
        marginBottom: 5,
        width: '95%',
        fontSize: 18,
        fontWeight: '300',
    },
    loadingOuter: {
        borderRadius: 80,
        height: 160,
        width: 160,
        backgroundColor: '#F3F5F7',
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadingInner: {
        position: 'absolute',
        borderRadius: 140 / 2,
        height: 140,
        width: 140,
        backgroundColor: '#ffffff',
        alignItems: 'center',
        justifyContent: 'center',
        shadowOffset: {width: 0, height: 5},
        shadowRadius: 8,
        shadowColor: 'black',
        shadowOpacity: 0.05,
        elevation: 1,
    },
    stackCarouselContainer: {
        flex: 0.25,
        width: '90%',
    },
    stackOuter: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    stackInner: {
        backgroundColor: '#ffffff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    stackCarousel: {
        flexDirection: 'row',
        padding: 20,
    },
    deviceTempContainer: {
        position: 'absolute',
        backgroundColor: '#ffffff',
        width: 120,
        height: 120,
        borderRadius: 120 / 2,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        shadowOffset: {width: 0, height: 5},
        shadowRadius: 8,
        shadowColor: 'black',
        shadowOpacity: 0.05,
        elevation: 1,
    },
    deviceTempGradient: {
        position: 'absolute',
        backgroundColor: '#ffffff',
        width: 180,
        height: 180,
        borderRadius: 180 / 2,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
    },
    deviceTempMask: {
        position: 'absolute',
        backgroundColor: '#ffffff',
        width: 170,
        height: 170,
        borderRadius: 170 / 2,
        overflow: 'hidden',
        borderColor: 'white',
        borderWidth: 0,
    },
    deviceTemp: {
        fontSize: 35,
        fontWeight: '300',
    },
    timeSchedule: {
        backgroundColor: '#ffffff',
        width: '90%',
        borderRadius: 10,
        marginTop: 20,
        padding: 15,
        shadowOffset: {width: 0, height: 5},
        shadowRadius: 8,
        shadowColor: 'black',
        shadowOpacity: 0.05,
        elevation: 1,
    },
    timeSelector: {
        flexDirection: 'row',
    },
    time: {
        flex: 1,
    },
    selectTime: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    scheduleDays: {
        flexDirection: 'row',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 20,
    },
    scheduleDay: {
        marginRight: 4,
        fontWeight: '700',
    },
    scheduleTime: {
        fontWeight: '300',
        fontSize: 24,
    },
    dayButton: {
        height: 30,
        width: 30,
        margin: 3,
        borderRadius: 30 / 2,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
    },
    dayButtonActive: {
        height: 30,
        width: 30,
        margin: 3,
        borderRadius: 30 / 2,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#94CB2B',
    },
    dialButton: {
        margin: 10,
        flex: 1,
        borderColor: 'white',
        borderWidth: 30,
        overflow: 'hidden',
        shadowColor: 'black',
        shadowRadius: 10,
        shadowOpacity: 1,
    },
    searchDealer: {
        backgroundColor: '#ffffff',
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#D8D8D8',
    },
    dataRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#D8D8D8',
        padding: 10,
    },
});

export default styles;
